feat: set env variables from github secrets & variables

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,14 +1,14 @@
-name: "Dokploy Deployment"
-description: "Trigger a Dokploy deployment"
+name: "Dokploy Deployment with GitHub secrets and variables"
+description: "Trigger a Dokploy deployment with GitHub secrets and variables"
 branding:
-  icon: "upload-cloud"
+  icon: "box"
   color: "gray-dark"
 inputs:
   dokploy_url:
     description: "Dokploy base URL, e.g. https://dokploy.example.com"
     required: true
-  auth_token:
-    description: "Dokploy authentication token"
+  api_key:
+    description: "Dokploy API key"
     required: true
   application_id:
     description: "Dokploy application/compose ID"
@@ -16,8 +16,18 @@ inputs:
   service_type:
     description: "Type of service (application,compose)"
     required: false
-    default: "application"
-
+  deploy:
+    description: "Boolean flag to trigger deployment"
+    required: false
+    default: true
+  secrets:
+    description: "secrets for the application"
+    required: false
+    default: null
+  vars:
+    description: "variables for the application"
+    required: false
+    default: null
 runs:
   using: "composite"
   steps:
@@ -33,24 +43,51 @@ runs:
             exit 1
             ;;
         esac
-
-    - name: Trigger Dokploy deployment
+    
+    - name: Set Environment Variables
+      if: ${{ inputs.secrets != null || inputs.vars != null }}
       shell: bash
-      env:
-        DOKPLOY_URL: ${{ inputs.dokploy_url }}
-        DOKPLOY_AUTH_TOKEN: ${{ inputs.auth_token }}
-        DOKPLOY_APPLICATION_ID: ${{ inputs.application_id }}
       run: |
+        format_json() {
+          local secrets="$1"
+          # Properly escape the string for inclusion in Dokploy application.saveEnvironment JSON body
+          # Also ignores github_ and GITHUB_ environment variables
+          echo "$secrets" | jq -r 'to_entries | map(select(.key | test("^(github_|GITHUB_)") | not)) | .[] | "\(.key)=\(.value)"' | sed ':a;N;$!ba;s/\n/\\n/g'
+        }
+
+        # Extracting both secrets & variables
+        formatted_secrets=$(format_json '${{ inputs.secrets }}')
+        formatted_vars=$(format_json '${{ inputs.vars }}')
+
+        envs="${formatted_secrets}\\n${formatted_vars}"
+
         response=$(curl -X 'POST' \
-          "$DOKPLOY_URL/api/${{ inputs.service_type }}.deploy" \
+          "${{ inputs.dokploy_url }}/api/application.saveEnvironment" \
           -H 'accept: application/json' \
           -H 'Content-Type: application/json' \
-          -H "Authorization: Bearer $DOKPLOY_AUTH_TOKEN" \
-          -d "{\"${{ inputs.service_type }}Id\": \"$DOKPLOY_APPLICATION_ID\"}" \
+          -H "x-api-key: ${{ inputs.api_key }}" \
+          -d "{\"${{ inputs.service_type }}Id\": \"${{ inputs.application_id }}\", \"env\": \"$envs\" }" \
           -w "%{http_code}" \
           -o /dev/null \
           -s)
+        if [ "$response" -ne 200 ]; then
+          echo "Setting environment variables failed with status code: $response"
+          exit 1
+        fi
 
+    - name: Trigger Dokploy deployment
+      if: ${{ inputs.deploy == 'true' }}
+      shell: bash
+      run: |
+        response=$(curl -X 'POST' \
+          "${{ inputs.dokploy_url }}/api/${{ inputs.service_type }}.deploy" \
+          -H 'accept: application/json' \
+          -H 'Content-Type: application/json' \
+          -H "x-api-key: ${{ inputs.api_key }}" \
+          -d "{\"${{ inputs.service_type }}Id\": \"${{ inputs.application_id }}\"}" \
+          -w "%{http_code}" \
+          -o /dev/null \
+          -s)
         if [ "$response" -ne 200 ]; then
           echo "Deployment failed with status code: $response"
           exit 1
